verifyDepsBeforeRun: false
allowBuilds:
  esbuild: true
  sharp: false
  unrs-resolver: false
overrides:
  brace-expansion: 5.0.8
  esbuild: 0.28.1
  postcss: 8.5.22
  sharp: 0.35.0
patchedDependencies:
  minimatch@3.1.5: patches/minimatch@3.1.5.patch
